const { ok } = require('node:assert')
const exported = require('../dist/index.cjs')

ok(typeof exported === 'object' && exported)
ok(typeof exported.getFetchConfiguration === 'function')
ok(typeof exported.setFetchConfiguration === 'function')
ok(typeof exported.willMockFetch === 'function')
ok(typeof exported.includesMockedFetch === 'function')
ok(typeof exported.mockFetch === 'function')
ok(typeof exported.unmockFetch === 'function')
ok(typeof exported.unmockAllFetches === 'function')
ok(typeof exported.isFetchReplaced === 'function')
ok(typeof exported.replaceFetch === 'function')
ok(typeof exported.restoreFetch === 'function')
