name: Build and Test or Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
  pull_request:

jobs:

  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v5
    - uses: pnpm/action-setup@v4
      with:
        version: latest
    - uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'
    - run: npm i -g npm
    - run: npm config ls -l
    - run: pnpm i --frozen-lockfile --no-verify-store-integrity
    - run: npm run build
    - run: npm test
    - run: npm publish --access public --verbose
    # - uses: prantlf/publish-release-action@v1
    #   if: ${{ github.ref_name == 'master' }}
    #   with:
    #     no-npm-auth: true
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
